version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    develop:
      watch:
        - action: sync
          path: ./frontend/src
          target: /app/src
          ignore:
            - node_modules/
            - .next/
            - "**/*.test.*"
        - action: sync
          path: ./frontend/public
          target: /app/public
        - action: sync+restart
          path: ./frontend/package.json
          target: /app/package.json

  api:
    build:
      context: ./backend
    container_name: api
    ports:
      - "8000:8000"
    depends_on:
      - mongo
      - ai_service_mock
    environment:
      - MONGO_DETAILS=mongodb://mongo:27017
      - AI_SERVICE_URL=http://ai_service_mock:5000
    develop:
      watch:
        - action: sync+restart
          path: ./backend/app
          target: /backend/app
          ignore:
            - "**/__pycache__/"
            - "**/*.pyc"
        - action: sync+restart
          path: ./backend/requirements.txt
          target: /backend/requirements.txt

  mongo:
    image: mongo:4.4
    container_name: mongo
    volumes:
      - mongo_data:/data/db

  ai_service_mock:
    build:
      context: ./backend/ai_service
    container_name: ai_service_mock
    ports:
      - "5000:5000"
    develop:
      watch:
        - action: sync
          path: ./backend/ai_service
          target: /app
          ignore:
            - "**/__pycache__/"
            - "**/*.pyc"

volumes:
  mongo_data:

